mineral_catalog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include, url
from mineral_catalog import views

urlpatterns = [  # DEFAULT VIEWS
    # index
    path('', views.index, name='index'),
    # Django admin
    path('admin/', admin.site.urls),
    # import minerals
    path('minerals/', include(
        ('minerals.urls', 'minerals'), namespace='minerals')),
]

# django-debug-toolbar:
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
       url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

minerals/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.conf import settings
from django.conf.urls import include, url

from minerals import views

urlpatterns = [ # LIST VIEWS:
    # show all minerals
    path('all/', views.all_minerals, name='all'),
]
urlpatterns += [  # FILTER VIEWS:
    # filter by first letter
    path('filter/letter/<str:query>',
         views.filter_by_first_letter, name='filter'),
    # filter by group
    path('filter/group/<str:query>', views.filter_by_group, name='group'),
    # filter by color
    path('filter/color/<str:query>', views.filter_by_color, name='color'),
]
urlpatterns += [  # SEARCH VIEWS:
    # search by name contains
    #   DEPRECATED - this function has been replaced by search.
    # path('search/', views.mineral_name_search, name='search'),
    # search by any field contains
    path('search/', views.mineral_all_search, name='search'),
]
urlpatterns += [  # DETAIL VIEWS:
    # show mineral details
    path('detail/<int:pk>', views.mineral_detail, name='detail'),
    # Show random mineral details
    path('random/', views.random_mineral, name='random'),
]
urlpatterns += staticfiles_urlpatterns()


# django-debug-toolbar:
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
       url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

templates/detail.html
{% extends "layout.html" %}
{% load under_space from templatetags %}
{% block title%}Maxwell's Minerals{% endblock title%}
{% block head %}
<div class="bounds">
  <div class="grid-100">
    <a href="/">
      <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
        <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 " />
        <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 " />
        <polygon
          points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 " />
      </svg>
      <h1 class="logo__name text-centered">Maxwell's Minerals</h1>
    </a>
    <p class="logo__text text-centered">This mineral rocks!</p>
  </div>
{% endblock head %}
  {% block content %}
  <div class="grid-100 mineral__container">
    <h1 class="mineral__name">{{ mineral.name }}</h1>
    <div class="mineral__image-bg">
      <img class="mineral__image" src="/static/images/{{ mineral.name }}.jpg">
      <p class="mineral__caption">{{ mineral.image_caption }}</p>
    </div>
    <div class="mineral__table-container">
      <table class="mineral__table">
        {% for kv in kv_list %}
        <tr>
          <td class="mineral__title">{{ kv.0 | title | under_space }}</td>
          <td class="mineral__category">{{ kv.1 | safe }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>
<div class="minerals__random">
  <a class="minerals__anchor" href="#">Show random mineral</a>
</div>
  {% endblock content %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<html>

<head>
    <title>
        {% block title %}
        {% endblock title %}
    </title>

    <head>
        <meta charset="utf-8">
        <title>Maxwell's Minerals: A magnificant catalog of minerals</title>
        <meta name="description" content="">
        <meta name="author" content="Maxwell Hunter">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
        <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Staatliches" rel="stylesheet" type='text/css'>
    </head>
    <link rel="stylesheet" href="/static/css/global.css">
</head>

<body>
    <div class="container">
        <div class="topbar fixed">
            <div class="grid-100 text-centered" id="searchSidebar">
                <form action="{% url 'minerals:search' %}" class=" grid-100 text-centered" method="post" name="search">
                    {% csrf_token %}
                    {{ SearchForm.search }}
                    <input id="searchButton" class="mineral__table text-centered" type='submit' value="SUBMIT">
                </form>
            </div>
            <div class="grid-100 text-centered" id="leftSidebar">
                FILTERS<br />
                <div class="grid-30 nopadding">
                    <div class="filterList">
                        Colors:<br />
                        {% for color in colors %}
                        <a href="{% url 'minerals:color' query=color %}" {% if color == color_listing %} id='filtered_color'
                            {% endif %}>

                            {{ color | title }}
                        </a><br />
                        {% endfor %}
                    </div>

                </div>
                <div class="grid-40 nopadding">
                    <div class="filterList">
                        Groups: <br />
                        {% for group_listing in groups %}
                        <a href="{% url 'minerals:group' query=group_listing %}" {% if group == group_listing %}
                            id='filtered_group' {% endif %}>

                            {{ group_listing }}
                        </a><br />
                        {% endfor %}
                    </div>
                </div>
                <div class="grid-30">
                    <p class="filterList">
                        Letter: </br>
                        {% for char in alphabet %}
                        {% if char == letter %}
                        <strong>
                            {% endif %}
                            <a href="{% url 'minerals:filter' query=char %}" {% if char == letter %} id='filtered_letter'
                                {% endif %}>
                                {{ char }}
                            </a>
                            {% if char == letter %}
                        </strong>
                        {% endif %}
                        {% endfor %}
                    </p>


                </div>
            </div>
        </div>
        <div class="grid-100" id="maincontent">

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
            </ul>
            {% endif %}

            {% block head %}
            {% endblock head %}

            <!--            <p class="text-centered">
                Filter by first letter: </br>
                {% for char in alphabet %}
                {% if char == letter %}
                <strong>
                    {% endif %}
                    <a href="{% url 'minerals:filter' query=char %}" {% if char == letter %} id='filtered_letter' {% endif %}>
                        {{ char }}
                    </a>
                    {% if char == letter %}
                </strong>
                {% endif %}
                {% endfor %}
            </p>
        -->

            {% if minerals is not None %}
            <h2 class="text-centered">
                {{ count }} minerals found
                {% if query %}
                for search query "{{ query }}"
                {% endif %}
                {% if letter %}
                that start with the letter "{{ letter }}"
                {% endif %}
                {% if group %}
                in the group "{{ group }}"
                {% endif %}
                {% if color_listing %}
                that have a "{{ color_listing }}" color
                {% endif %}
            </h2>
            {% endif %}
            {% block content %}
            {% endblock content %}
            <p class="text-centered">
                <a href="http://github.com/mhunterak" target="_blank">by @mHunterAk</a>
            </p>

        </div>
        <div class="minerals__random">
            <a class="minerals__anchor" href="{% url 'minerals:random' %}">Show random mineral</a>
        </div>
</body>
</html>

templates/list.html
{% extends "layout.html" %}
{% block title%}Maxwell's Minerals{% endblock title%}

{% block head %}
<div class="bounds">
  <div class="grid-100">
    <a href="{% url 'index' %}">
      <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
        <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 " />
        <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 " />
        <polygon
          points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 " />
      </svg>
      <h1 class="logo__name text-centered">Maxwell's Minerals</h1>
    </a>
    <p class="logo__text text-centered">
      They're not rocks, but they totally rock!
    </p>
  </div>
{% endblock head %}


{% block content %}
  {% if count %}
  <div class="grid-100">
    <ul class="minerals__container text-centered">
      {% for mineral in minerals %}
      <li class="minerals__item">
        <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.id %}"
          style="display:inline-block;">{{ mineral.name }}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
</div>
{% endblock content%}